### PR TITLE
rk - fixed BUG: Disallow ability to navigate to commons not created yet

### LINKED ISSUE #33: BUG: Disallow ability to navigate to commons not created yet
Summary
If a user has not created a commons, they can navigate to the URL for that commons and get an undefined page. 

Expected Behavior
The user should be able to see some dialogue that indicates that this commons has not been created yet. 

Current / Observed Behavior
This is the current behavior:

Image

Steps to Reproduce
Navigate to the https://happycows.dokku-XX.cs.ucsb.edu/play/{commonsId} where commonsId is that of a commons that has not been created yet 
Observe the behavior

### PR DESCRIPTION
**Pull request by rainakakani21**
## Overview

In this PR, I added a functionality to catch when users try to navigate to a commons that have not been created yet. It is similar to my previous PR on disallowing the ability to navigate to unjoined commons.

## Screenshots 
Screenshot 2024-05-28 at 11 59 55 PM

## Feedback Request

Please give suggestions on the following:
- I would appreciate any advice on how to get rid of the pop up error messages

## Future Possibilities 

Some possible points could be:
- In the future, it might be possible to redirect users to another page instead of simply displaying a text error message 

## Validation (Optional)

- login to happy cows on this deployment: https://proj-happycows-rk.dokku-08.cs.ucsb.edu/
- in the search bar, add /play/commonsID to the end of the url where commonsID is the id of the commons that you did not create
- observe the message: "This commons does not exist!"

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #33

### CODE REVIEW

**Review by Jumshim — DISMISSED** [review]
LGTM!

File: frontend/src/main/pages/PlayPage.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ export default function PlayPage() {
     );
     // Stryker restore all
 
-    const commonsPlusExists = !(typeof commonsPlus == 'undefined'); 
+    const commonsPlusExists = !(typeof commonsPlus == 'undefined'); // does the commons exist?
```
Comment (sangitakunapuli) [inline frontend/src/main/pages/PlayPage.js]: please remove this comment!

**Review by sangitakunapuli — DISMISSED** [review]
LGTM

File: frontend/src/main/pages/PlayPage.js (hunk 1 above)
Comment (rainakakani21) [reply frontend/src/main/pages/PlayPage.js]: done!

**Review by vaaniarora — APPROVED** [review]
lgtm!

**Review by sangitakunapuli — APPROVED** [review]
LGTM
