### PR TITLE
rk - fixed the date issue, just had to change timezone

### LINKED ISSUE #8: BUG: Change default start date when creating a commons to be today's date
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

Currently, when creating a new commons, the start date is set to the next day, so the commons cannot be immediately joined after creation. It would make more sense for the new commons to start on the present day, so this can be remedied with this bug fix.

### Expected Behavior

Creating a commons has the default day of today's date.

### Current / Observed Behavior

Creating a commons has the default day of tomorrow's date.

### Steps to Reproduce

1. As admin, navigate to the create commons page and create a new commons.
2. Observe that the date is not today's date.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by rainakakani21**
## Overview

In this PR, I changed default start date when creating a commons to be today's date. I changed the timezone for the starting date to be local to Canada (bc of date formatting).

## Screenshots (Optional)
Screenshot 2024-05-29 at 11 41 56 PM

## Validation (Optional)

- Go to https://proj-happycows-rk.dokku-08.cs.ucsb.edu
- Create a commons
- Observe that the starting date is always today's date. 

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #8

### CODE REVIEW

**Review by emilythai — DISMISSED** [review]
LGTM!

File: frontend/src/main/components/Commons/CommonsForm.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ function CommonsForm({initialCommons, submitAction, buttonLabel = "Create"}) {
     
     const testid = "CommonsForm";
     const curr = new Date();
-    const today = curr.toISOString().split('T')[0];
+    const today = curr.toLocaleDateString('en-CA');
```
Comment (pconrad) [inline frontend/src/main/components/Commons/CommonsForm.js]: I don't think en-CA means what you think it means:

image

maybe you want `en-US` ?

**Review by pconrad — CHANGES_REQUESTED** [review]

File: frontend/src/main/components/Commons/CommonsForm.js (hunk 1 above)
Comment (rainakakani21) [reply frontend/src/main/components/Commons/CommonsForm.js:73]: Oh I see.. It's the language. I'll change them to US english.

Comment (rainakakani21) [reply frontend/src/main/components/Commons/CommonsForm.js]: I think its necessary to use canadian english because it formats the date as YYYY-MM-DD (and thats the format that the code is working with). American english uses the format MM/DD/YYYY. 

Would it be appropriate to keep it as canadian english?

Comment (pconrad) [reply frontend/src/main/components/Commons/CommonsForm.js]: Ah, I see.    In that case, yes, but let's comment that so that we understand the rationale.  This will not necessarily be obvious to the reader.

Comment (pconrad) [inline frontend/src/main/components/Commons/CommonsForm.js]:
```suggestion
    const today = curr.toLocaleDateString('en-CA'); // Canadian english gives YYYY-MM-DD
```

File: frontend/src/tests/components/Commons/CommonsForm.test.js [hunk 2]
```diff
@@ -154,7 +154,7 @@ describe("CommonsForm tests", () => {
   it("Check Default Values and correct styles", async () => {
 
     const curr = new Date();
-    const today = curr.toISOString().substr(0, 10);
+    const today = curr.toLocaleDateString('en-CA');
```
Comment (pconrad) [inline frontend/src/tests/components/Commons/CommonsForm.test.js]:
```suggestion
    const today = curr.toLocaleDateString('en-CA'); // Canadian english gives YYYY-MM-DD
```

File: frontend/src/tests/components/Commons/CommonsForm.test.js [hunk 3]
```diff
@@ -288,7 +288,7 @@ describe("CommonsForm tests", () => {
 
   it("renders correctly when an initialCommons is not passed in", async () => {
     const curr = new Date();
-    const today = curr.toISOString().substr(0, 10);
+    const today = curr.toLocaleDateString('en-CA');
```
Comment (pconrad) [inline frontend/src/tests/components/Commons/CommonsForm.test.js]:
```suggestion
    const today = curr.toLocaleDateString('en-CA'); // Canadian english gives YYYY-MM-DD
```

File: frontend/src/tests/components/Commons/CommonsForm.test.js [hunk 4]
```diff
@@ -360,7 +360,7 @@ test("the correct parameters are passed to useBackend", async () => {
   test("populates form fields with default values when initialCommons is not provided", async () => {
 
     const curr = new Date();
-    const today = curr.toISOString().substr(0, 10);
+    const today = curr.toLocaleDateString('en-CA');
```
Comment (pconrad) [inline frontend/src/tests/components/Commons/CommonsForm.test.js]:
```suggestion
    const today = curr.toLocaleDateString('en-CA'); // Canadian english gives YYYY-MM-DD
```

**Review by pconrad — CHANGES_REQUESTED** [review]
Here are four suggested changes; let me know if I've understood your intent.

 You can just click each one to accept it, if you are ok with this.

This will make the PR mergeable.

**Comment by pconrad** [comment]
Closing since this PR still has testing errors (Monday 06/03, well after the final deadline).

**Comment by pconrad** [comment]
Ouch.. sorry... closed wrong PR.

**Comment by rainakakani21** [comment]
> Here are four suggested changes; let me know if I've understood your intent.
> 
> You can just click each one to accept it, if you are ok with this.
> 
> This will make the PR mergeable.

I understand that future programmers might not understand why I chose Canadian english. I've accepted the changes you suggested!

**Review by vaaniarora — APPROVED** [review]
lgtm!

**Review by pconrad — APPROVED** [review]
LGTM!
